NATIONALS_RU = {
    'abazin': 'Абазины',
    'abkhaz': 'Абхазы',
    'avar': 'Аварцы',
    'bezhtin': 'Бежтинцы',
    'adygei': 'Адыгейцы',
    'azerbaijani': 'Азербайджанцы',
    'aleut': 'Алеуты',
    'altai': 'Алтайцы',
    'tubalar': 'Тубалары',
    'arab': 'Арабы',
    'armenian': 'Армяне',
    'assyrian': 'Ассирийцы',
    'afghan': 'Афганцы',
    'balkar': 'Балкарцы',
    'bashkir': 'Башкиры',
    'belarusian': 'Белорусы',
    'bulgarian': 'Болгары',
    'buryat': 'Буряты',
    'veps': 'Вепсы',
    'gagauz': 'Гагаузы',
    'greek': 'Греки',
    'georgian': 'Грузины',
    'ingiloi': 'Ингилойцы',
    'dargin': 'Даргинцы',
    'dolgan': 'Долганы',
    'jew': 'Евреи',
    'ingush': 'Ингуши',
    'kabardian': 'Кабардинцы',
    'kazakh': 'Казахи',
    'kalmyk': 'Калмыки',
    'karachai': 'Карачаевцы',
    'kyrgyz': 'Киргизы',
    'chinese': 'Китайцы',
    'komi': 'Коми-пермяки',
    'korean': 'Корейцы',
    'crimean_tatar': 'Крымские татары',
    'kumandin': 'Кумандинцы',
    'kumyk': 'Кумыки',
    'lak': 'Лакцы',
    'latvian': 'Латыши',
    'lezgin': 'Лезгины',
    'lithuanian': 'Литовцы',
    'mari': 'Марийцы',
    'moldovan': 'Молдаване',
    'mordvin': 'Мордва',
    'moksha': 'Мордва-мокша',
    'erzya': 'Мордва-эрзя',
    'nagaibak': 'Нагайбаки',
    'german': 'Немцы',
    'ossetian': 'Осетины',
    'digor': 'Осетины-дигорцы',
    'polish': 'Поляки',
    'russian': 'Русские',
    'cossack': 'Казаки',
    'rutul': 'Рутульцы',
    'soyot': 'Сойоты',
    'central_asian_jew': 'Среднеазиатские евреи',
    'tabasaran': 'Табасараны',
    'tajik': 'Таджики',
    'talysh': 'Талыши',
    'tatar': 'Татары',
    'siberian_tatar': 'Сибирские татары',
    'tuvan': 'Тувинцы',
    'turk': 'Турки',
    'turkmen': 'Туркмены',
    'udmurt': 'Удмурты',
    'uzbek': 'Узбеки',
    'uyghur': 'Уйгуры',
    'ukrainian': 'Украинцы',
    'khakas': 'Хакасы',
    'tsakhur': 'Цахуры',
    'gypsy': 'Цыгане',
    'circassian': 'Черкесы',
    'chechen': 'Чеченцы',
    'chuvash': 'Чуваши',
    'chukchi': 'Чукчи',
    'shor': 'Шорцы',
    'evenk': 'Эвенки',
    'even': 'Эвены',
    'yukaghir': 'Юкагиры',
    'yakut': 'Якуты'
}

def get_russian_name(eng_name):
    return NATIONALS_RU.get(eng_name.lower(), eng_name.capitalize())

def get_english_name(ru_name):
    for eng, rus in NATIONALS_RU.items():
        if rus.lower() == ru_name.lower():
            return eng
    return ru_name.lower()
